name: Dependabot Automerge

on:
  workflow_run:
    types:
      - completed
    workflows:
      - 'Branch Build Validation'

  workflow_dispatch:

jobs:
  merge-me:
    name: Automerge minor updates

    runs-on: ubuntu-latest

    steps:
      - name: Automerge PR with mino updates to dependencies
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        uses: ridedott/merge-me-action@v2
        with:
          GITHUB_TOKEN: ${{ secrets.DEPENDABOT_AUTOMERGE_TOKEN }}
          PRESET: DEPENDABOT_MINOR
